name: build-rtsp-image

on:
  push:
    paths:
    - "producer-cpp/docker-linux/**"
    - ".github/workflows/build-rtsp-image.yml"

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: login to docker hub registry
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo ${{ secrets.DH_PAT }} | docker login --username Balou9 --password-stdin

      - name: build rtsp docker image
        run: |
          docker build . \
          --file ./producer-cpp/docker-linux/Dockerfile \
          --tag spyci-images/rtsp:latest

      - name: push image to docker hub registry
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/spyci-images
