name: build-rtsp-image

env:
  IMAGE_TAG: rtsp

on:
  push:
    paths:
    - "producer/docker-rtsp/**"
    - ".github/workflows/build-rtsp-image.yml"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: build docker image
        run: |
          docker build . \
          --file ./producer/docker-${{ env.IMAGE_TAG }}/Dockerfile \
          --tag icydigital/spyci-images:${{ env.IMAGE_TAG }}

      - name: login to github container registry
        run: |
          echo "${{ secrets.CR_PAT }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: push image to github container registry
        run: |
          docker push ghcr.io/icydigital/spyci-images:${{ env.IMAGE_TAG }}

      - name: logs out from github container registry
        run: |
          docker logout ghcr.io
