name: build-rtsp-docker-image

on:
  push:
    paths:
    - "producer-cpp/docker-linux/Dockerfile"
    - ".github/workflows/cd.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: login to github container registry
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u Balou9 --password-stdin

      - name: build rtsp docker image
        run: |
          docker build \
          -q \
          -t rtsp_docker \
            ./producer-cpp/docker-linux

      - name: retrieve rtsp docker image id
        run: |
          echo "IMAGE_ID=$(docker images -q rtsp_docker)" >> $GITHUB_ENV

      - name: observe rtsp docker image id
        run: |
          printf "${{ env.IMAGE_ID }}"
